server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetach-register: false
    service-url:
        #指向其他eureka集群服务地址
#      defaultZone: http://eureka7002.com:7002/eureka/
        #单机模式指向自己
        defaultZone: http://eureka7001.com:7001/eureka/
#  server:
#      #关闭自我保护模式
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 1
spring:
  datasource:
    url: jdbc:mysql://182.92.179.85:3306/db2019?userUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: cms_user
    password: cms_12345678..
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource