server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://182.92.179.85:3306/db2019?userUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: cms_user
    password: cms_12345678..
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
mybatis-plus:
  configuration:
    call-setters-on-nulls: true
# 设置openfeign客户端超时时间（openfeign默认包含ribbon）
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  level:
    com:
      atguigu:
        springcloud:
          service:
            PaymentFeignService: debug